language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t soniccc/docker-react -f Dockerfile.dev .

script:
  - docker run sonicc/docker-react npm run test -- --coverage
